# Generated by Django 2.0.8 on 2018-09-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPlanHouse',
            fields=[
                ('si_no', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField(editable=False)),
                ('end_date', models.DateTimeField(editable=False)),
            ],
        ),
    ]
