# Generated by Django 2.0.8 on 2018-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterplanhouse',
            options={'ordering': ('activity',)},
        ),
        migrations.AlterField(
            model_name='masterplanhouse',
            name='end_date',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='masterplanhouse',
            name='start_date',
            field=models.CharField(max_length=256),
        ),
    ]
